default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: semantic-es_development

test:
  <<: *default
  database: semantic-es_test

production:
  <<: *default
  database: semantic-es_production
  username: semantic-es
  password: <%= ENV['SEMANTIC-ES_DATABASE_PASSWORD'] %>
